### ISSUE TITLE
23:30 traceback with some settings

### ISSUE THREAD

**Issue by badguy99** [badguy99/octoblock#6]
```
2020-04-23 23:30:01.633434 WARNING octo_block_90minutes_for_vacuum: ------------------------------------------------------------
2020-04-23 23:30:01.638258 WARNING octo_block_90minutes_for_vacuum: Unexpected error in worker for App octo_block_90minutes_for_vacuum:
2020-04-23 23:30:01.646222 WARNING octo_block_90minutes_for_vacuum: Worker Ags: {'id': '9aa9003cfed74bd6ada30890da3a30b8', 'name': 'octo_block_90minutes_for_vacuum', 'objectid': '34194df387b64845bc549fa5e6f20743', 'type': 'scheduler', 'function': <bound method OctoBlock.period_and_cost_callback of <octoblock.OctoBlock object at 0x7f937d9d00>>, 'pin_app': True, 'pin_thread': 2, 'kwargs': {'interval': 3600, '__thread_id': 'thread-2'}}
2020-04-23 23:30:01.661326 WARNING octo_block_90minutes_for_vacuum: ------------------------------------------------------------
2020-04-23 23:30:01.697477 WARNING octo_block_90minutes_for_vacuum: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/threading.py", line 766, in worker
    funcref(self.AD.sched.sanitize_timer_kwargs(app, args["kwargs"]))
  File "/config/appdaemon/apps/octoblock/octoblock.py", line 75, in period_and_cost_callback
    self.get_period_and_cost(region, d, limit_end)
  File "/config/appdaemon/apps/octoblock/octoblock.py", line 135, in get_period_and_cost
    tariffresults = tariff[u'results']
KeyError: 'results'
2020-04-23 23:30:01.709260 WARNING octo_block_90minutes_for_vacuum: ------------------------------------------------------------
```

comes out from:
```
octo_block_90minutes_for_vacuum:
  module: octoblock
  class: OctoBlock
  region: H
  hour: 1.5
  start_period: today
  use_timezone: True
  limits:
    start_time: '07:00'
    end_time: '16:00'
```

But not seen on 5hr block that also has start_period: today

**Comment by badguy99** [comment]
This happens when using `start_period: today` and `end_time` together. Currently testing a fix.
